#!/usr/bin/env python3
"""
程序入口
"""
import sys
from PyQt5.QtWidgets import QApplication
from .main_window import HumanAnimationSystem

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = HumanAnimationSystem()
    window.show()
    sys.exit(app.exec_())
